ONSdigital/dp-dimension-search-api

swagger.yaml

Include specification for search api.
Only includes endpoint for searching against a filtered instance where
dimensions have a hierarchy.
Check documentation makes sense and meets the needs for API and web customers.
A member from team A and team B

Initial spec for search api

---

service/service.go
vendor/github.com/ONSdigital/go-ns/elasticsearch/healthcheck.go
vendor/vendor.json

Add AWS auth signing to elasticsearch healthcheck

Add AWS auth signing to elasticsearch healthcheck

---

README.md
api/api.go
api/search.go
api/search_test.go
config/config.go
config/config_test.go
main.go
mocks/searchQueue.go
models/models.go
searchOutputQueue/searchOutputQueue.go
searchOutputQueue/searchOutputQueue_test.go
service/service.go

New endpoint to enable the api the ability (if authenticated) to kick off a search build of a particular hierarchy (dimension) of an instance.
Already been reviewed and merged into cmd-develop, and tested in environment.
Anyone

New endpoint to enable creation of an index

---

api/search.go
config/config.go
config/config_test.go
main.go
service/service.go

Pass service token instead of dataset API auth token
Review / test
Anyone

Pass service token instead of dataset API auth token

---

api/api.go
api/search_test.go
config/config.go
config/config_test.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/identity/authentication.go
vendor/github.com/ONSdigital/go-ns/handlers/requestID/handler.go
vendor/github.com/ONSdigital/go-ns/identity/authentication.go
vendor/github.com/ONSdigital/go-ns/identity/identity.go
vendor/vendor.json

Update identity middleware to force auth
Review changes
Anyone

Update identity middleware to force auth

---

api/api.go
api/search_test.go
service/service.go
vendor/github.com/ONSdigital/go-ns/healthcheck/middleware.go
vendor/vendor.json

* Only inject identity middleware when running in publishing
* Remove unused parameters
Review changes

Only inject identity middleware when running in publishing

---

swagger.yaml

Update summaries and descriptions to standardize for dev site
Check swagger spec is still valid
Check updates make things clearer
Anyone

Update title and descriptions to be more descriptive

---

swagger.yaml

Remove offset and limit from specs because they're not used parameters right now
Check spec is true and offset and limit have been removed as parameters
Anyone

Update description for limit parameter in spec

---

api/search.go
vendor/github.com/ONSdigital/go-ns/audit/audit.go
vendor/github.com/ONSdigital/go-ns/audit/log.go
vendor/github.com/ONSdigital/go-ns/avro/avro.go
vendor/github.com/ONSdigital/go-ns/avro/test_data.go
vendor/github.com/ONSdigital/go-ns/clients/identity/authentication.go
vendor/github.com/ONSdigital/go-ns/common/client.go
vendor/github.com/ONSdigital/go-ns/common/errors.go
vendor/github.com/ONSdigital/go-ns/common/identity.go
vendor/github.com/ONSdigital/go-ns/handlers/requestID/handler.go
vendor/github.com/ONSdigital/go-ns/log/log.go
vendor/github.com/ONSdigital/go-ns/rchttp/client.go
vendor/github.com/go-avro/avro/CHANGELOG.md
vendor/github.com/go-avro/avro/README.md
vendor/github.com/go-avro/avro/codegen.go
vendor/github.com/go-avro/avro/data_file.go
vendor/github.com/go-avro/avro/datum_reader.go
vendor/github.com/go-avro/avro/datum_writer.go
vendor/github.com/go-avro/avro/decoder.go
vendor/github.com/go-avro/avro/doc.go
vendor/github.com/go-avro/avro/encoder.go
vendor/github.com/go-avro/avro/errors.go
vendor/github.com/go-avro/avro/schema.go
vendor/github.com/go-avro/avro/schema_prepared.go
vendor/vendor.json

* vendor the latest avro package from go-ns to support maps
* fix error when logging audit failure - switch statement was using the wrong value.
Review changes
Anyone

Fix auditing error

---

vendor/github.com/gorilla/mux/AUTHORS
vendor/github.com/gorilla/mux/ISSUE_TEMPLATE.md
vendor/github.com/gorilla/mux/LICENSE
vendor/github.com/gorilla/mux/README.md
vendor/github.com/gorilla/mux/context_gorilla.go
vendor/github.com/gorilla/mux/context_native.go
vendor/github.com/gorilla/mux/doc.go
vendor/github.com/gorilla/mux/go.mod
vendor/github.com/gorilla/mux/middleware.go
vendor/github.com/gorilla/mux/mux.go
vendor/github.com/gorilla/mux/regexp.go
vendor/github.com/gorilla/mux/route.go
vendor/github.com/gorilla/mux/test_helpers.go
vendor/vendor.json

As the title describes
Check unit tests pass and successfully built in environment
Anyone

Vendor in gorilla mux package

---

dp-search-api.nomad

Using docker reduces the likelihood of timeout on deploy
check for typos
check repo names are consistent
check web/publishing both updated
anyone

Update nomad plan to use docker instead of exec driver

---

dp-search-api.nomad

What
Fix smart for double quotes
How to review
check quotes are not crazy
Who can review
anyone

Fix smart for double quotes

---

vendor/github.com/ONSdigital/go-ns/LICENSE.md
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/github.com/ONSdigital/go-ns/common/collection.go
vendor/github.com/ONSdigital/go-ns/common/rchttp.go
vendor/vendor.json

update datasetAPI client

---

api/search.go
api/search_test.go
vendor/github.com/jtolds/gls/stack_tags.go
vendor/vendor.json

Increase the default limit for items returned by the dimension search to 50
Search without supplying a limit and the default limit should be 50 instead of 20. 
Anyone but me

Update search api limit to 50

---

scripts/.gitignore
scripts/create-reindex-script.sh

script to create an adhoc script (a snapshot) for reindexing elasticsearch for instances
run the script, check the output (that is another script)
Not I.

add create-reindex-script.sh - builds script to reindex elasticsearch for all instances

---

dp-search-api.nomad

Update nomad plan to use new health check endpoint
Sanity check
Anyone

Update nomad plan to use new health check endpoint

---

dp-search-api.nomad
main.go
service/service.go

Do not health check audit producer in web environment

Do not health check audit producer in web environment

---

main.go

Do not health check Zebedee in web environment

Do not health check Zebedee in web environment

---

main.go

**Describe what you have changed and why.**
- Change log.Namespace to dp-dimension-search-api
- It is part of the process of renaming `dp-search-api` to `dp-dimension-search-api`
**Describe the steps required to test the changes.**
- Check if code change makes sense (spelling as well)
**Describe who worked on the changes, so that other people can review.**
Anyone - Justin made the changes

changing log.Namespace to dp-dimension-search-api

---

Dockerfile.concourse
Makefile
README.md
api/api.go
api/elasticsearch.go
api/search.go
api/search_test.go
ci/audit.yml
ci/build.yml
ci/scripts/audit.sh
ci/scripts/build.sh
ci/scripts/unit.sh
ci/unit.yml
config/config_test.go
dp-search-api.nomad
elasticsearch/api.go
go.mod
main.go
mocks/datasetapi.go
mocks/elasticsearch.go
mocks/searchQueue.go
models/model.go
service/service.go

**Describe what you have changed and why.**
- Update occurrence of `dp-search-api` to `dp-dimension-search-api`
**Describe the steps required to test the changes.**
- Check if the changes make sense
- Check if any occurrences are missed out
**Describe who worked on the changes, so that other people can review.**
Anyone - Justin made the changes

update occurrence of dp-search-api to dp-dimension-search-api

---

README.md
api/api.go
api/search_test.go
scripts/create-reindex-script.sh
swagger.yaml

**Describe what you have changed and why.**
- Update route from `/search` to `/dimension-search` (change made in `api/api.go`)
- Update change in swagger spec
- Update change in tests and change other occurrences of `/search` to `/dimension-search`
**Describe the steps required to test the changes.**
- Check if the code change is valid
- Check if all occurrences of `/search` have been changed to `/dimension-search`
**Describe who worked on the changes, so that other people can review.**
Anyone - Justin made the changes

update route to /dimension-search and other occurences

---

LICENSE.md
README.md

See title
Check licensing dates are correct
Anyone

Update licensing dates

---

elasticsearch/api.go
go.mod
go.sum

See title
Check changes make sense
Anyone

Use new auth package in dp-elasticsearch to sign aws requests

---

api/search.go
elasticsearch/api.go
mocks/elasticsearch.go
models/model.go

Update response struct to support ES7 but with an alternative struct for ES6 compatibility.
NB this is an alternative approach to PR #100 
Check tests pass and code makes sense.
Anyone but me

Add temporary code for migration between ES6 and ES7 (alternative approach)

---

elasticsearch/api.go

Added log line for case where unmarshalling to the default (ES7) struct fails.
Check code makes sense and tests pass.
Anyone but me

Add logging when unable to unmarshal ES7 response

---

.golangci.yml
Makefile
api/search.go
api/search_test.go
ci/scripts/lint.sh
config/config_test.go
models/models_test.go
searchoutputqueue/searchOutputQueue_test.go

.golangci.yml file set to new standards
Check changes are ok and CI passes 
Anyone

using new linting standards
